/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerformanceReportRouteImport } from './routes/performance-report'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IntakeRouteImport } from './routes/intake'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIdRouteImport } from './routes/jobs.$id'
import { Route as ApiSyncCalendarRouteImport } from './routes/api/sync-calendar'
import { Route as ApiSendReportRouteImport } from './routes/api/send-report'
import { Route as ApiPrefillReportRouteImport } from './routes/api/prefill-report'
import { Route as ApiImportCalendarRouteImport } from './routes/api/import-calendar'
import { Route as ApiDriveUploadRouteImport } from './routes/api/drive-upload'
import { Route as ApiDriveCustomerFilesRouteImport } from './routes/api/drive-customer-files'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminNewRouteImport } from './routes/admin.new'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as ApiPublicHooksOrganizeDriveRouteImport } from './routes/api/public/hooks/organize-drive'
import { Route as ApiPublicHooksFindFolderRouteImport } from './routes/api/public/hooks/find-folder'

const PerformanceReportRoute = PerformanceReportRouteImport.update({
  id: '/performance-report',
  path: '/performance-report',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IntakeRoute = IntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIdRoute = JobsIdRouteImport.update({
  id: '/jobs/$id',
  path: '/jobs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSyncCalendarRoute = ApiSyncCalendarRouteImport.update({
  id: '/api/sync-calendar',
  path: '/api/sync-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSendReportRoute = ApiSendReportRouteImport.update({
  id: '/api/send-report',
  path: '/api/send-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrefillReportRoute = ApiPrefillReportRouteImport.update({
  id: '/api/prefill-report',
  path: '/api/prefill-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImportCalendarRoute = ApiImportCalendarRouteImport.update({
  id: '/api/import-calendar',
  path: '/api/import-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveUploadRoute = ApiDriveUploadRouteImport.update({
  id: '/api/drive-upload',
  path: '/api/drive-upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveCustomerFilesRoute = ApiDriveCustomerFilesRouteImport.update({
  id: '/api/drive-customer-files',
  path: '/api/drive-customer-files',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNewRoute = AdminNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksOrganizeDriveRoute =
  ApiPublicHooksOrganizeDriveRouteImport.update({
    id: '/api/public/hooks/organize-drive',
    path: '/api/public/hooks/organize-drive',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksFindFolderRoute =
  ApiPublicHooksFindFolderRouteImport.update({
    id: '/api/public/hooks/find-folder',
    path: '/api/public/hooks/find-folder',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/performance-report': typeof PerformanceReportRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/drive-customer-files': typeof ApiDriveCustomerFilesRoute
  '/api/drive-upload': typeof ApiDriveUploadRoute
  '/api/import-calendar': typeof ApiImportCalendarRoute
  '/api/prefill-report': typeof ApiPrefillReportRoute
  '/api/send-report': typeof ApiSendReportRoute
  '/api/sync-calendar': typeof ApiSyncCalendarRoute
  '/jobs/$id': typeof JobsIdRoute
  '/api/public/hooks/find-folder': typeof ApiPublicHooksFindFolderRoute
  '/api/public/hooks/organize-drive': typeof ApiPublicHooksOrganizeDriveRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/performance-report': typeof PerformanceReportRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/drive-customer-files': typeof ApiDriveCustomerFilesRoute
  '/api/drive-upload': typeof ApiDriveUploadRoute
  '/api/import-calendar': typeof ApiImportCalendarRoute
  '/api/prefill-report': typeof ApiPrefillReportRoute
  '/api/send-report': typeof ApiSendReportRoute
  '/api/sync-calendar': typeof ApiSyncCalendarRoute
  '/jobs/$id': typeof JobsIdRoute
  '/api/public/hooks/find-folder': typeof ApiPublicHooksFindFolderRoute
  '/api/public/hooks/organize-drive': typeof ApiPublicHooksOrganizeDriveRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/intake': typeof IntakeRoute
  '/login': typeof LoginRoute
  '/performance-report': typeof PerformanceReportRoute
  '/admin/new': typeof AdminNewRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/drive-customer-files': typeof ApiDriveCustomerFilesRoute
  '/api/drive-upload': typeof ApiDriveUploadRoute
  '/api/import-calendar': typeof ApiImportCalendarRoute
  '/api/prefill-report': typeof ApiPrefillReportRoute
  '/api/send-report': typeof ApiSendReportRoute
  '/api/sync-calendar': typeof ApiSyncCalendarRoute
  '/jobs/$id': typeof JobsIdRoute
  '/api/public/hooks/find-folder': typeof ApiPublicHooksFindFolderRoute
  '/api/public/hooks/organize-drive': typeof ApiPublicHooksOrganizeDriveRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/intake'
    | '/login'
    | '/performance-report'
    | '/admin/new'
    | '/admin/users'
    | '/api/drive-customer-files'
    | '/api/drive-upload'
    | '/api/import-calendar'
    | '/api/prefill-report'
    | '/api/send-report'
    | '/api/sync-calendar'
    | '/jobs/$id'
    | '/api/public/hooks/find-folder'
    | '/api/public/hooks/organize-drive'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/intake'
    | '/login'
    | '/performance-report'
    | '/admin/new'
    | '/admin/users'
    | '/api/drive-customer-files'
    | '/api/drive-upload'
    | '/api/import-calendar'
    | '/api/prefill-report'
    | '/api/send-report'
    | '/api/sync-calendar'
    | '/jobs/$id'
    | '/api/public/hooks/find-folder'
    | '/api/public/hooks/organize-drive'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/intake'
    | '/login'
    | '/performance-report'
    | '/admin/new'
    | '/admin/users'
    | '/api/drive-customer-files'
    | '/api/drive-upload'
    | '/api/import-calendar'
    | '/api/prefill-report'
    | '/api/send-report'
    | '/api/sync-calendar'
    | '/jobs/$id'
    | '/api/public/hooks/find-folder'
    | '/api/public/hooks/organize-drive'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  IntakeRoute: typeof IntakeRoute
  LoginRoute: typeof LoginRoute
  PerformanceReportRoute: typeof PerformanceReportRoute
  ApiDriveCustomerFilesRoute: typeof ApiDriveCustomerFilesRoute
  ApiDriveUploadRoute: typeof ApiDriveUploadRoute
  ApiImportCalendarRoute: typeof ApiImportCalendarRoute
  ApiPrefillReportRoute: typeof ApiPrefillReportRoute
  ApiSendReportRoute: typeof ApiSendReportRoute
  ApiSyncCalendarRoute: typeof ApiSyncCalendarRoute
  JobsIdRoute: typeof JobsIdRoute
  ApiPublicHooksFindFolderRoute: typeof ApiPublicHooksFindFolderRoute
  ApiPublicHooksOrganizeDriveRoute: typeof ApiPublicHooksOrganizeDriveRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/performance-report': {
      id: '/performance-report'
      path: '/performance-report'
      fullPath: '/performance-report'
      preLoaderRoute: typeof PerformanceReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intake': {
      id: '/intake'
      path: '/intake'
      fullPath: '/intake'
      preLoaderRoute: typeof IntakeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$id': {
      id: '/jobs/$id'
      path: '/jobs/$id'
      fullPath: '/jobs/$id'
      preLoaderRoute: typeof JobsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sync-calendar': {
      id: '/api/sync-calendar'
      path: '/api/sync-calendar'
      fullPath: '/api/sync-calendar'
      preLoaderRoute: typeof ApiSyncCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/send-report': {
      id: '/api/send-report'
      path: '/api/send-report'
      fullPath: '/api/send-report'
      preLoaderRoute: typeof ApiSendReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/prefill-report': {
      id: '/api/prefill-report'
      path: '/api/prefill-report'
      fullPath: '/api/prefill-report'
      preLoaderRoute: typeof ApiPrefillReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/import-calendar': {
      id: '/api/import-calendar'
      path: '/api/import-calendar'
      fullPath: '/api/import-calendar'
      preLoaderRoute: typeof ApiImportCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive-upload': {
      id: '/api/drive-upload'
      path: '/api/drive-upload'
      fullPath: '/api/drive-upload'
      preLoaderRoute: typeof ApiDriveUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive-customer-files': {
      id: '/api/drive-customer-files'
      path: '/api/drive-customer-files'
      fullPath: '/api/drive-customer-files'
      preLoaderRoute: typeof ApiDriveCustomerFilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/new': {
      id: '/admin/new'
      path: '/new'
      fullPath: '/admin/new'
      preLoaderRoute: typeof AdminNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/organize-drive': {
      id: '/api/public/hooks/organize-drive'
      path: '/api/public/hooks/organize-drive'
      fullPath: '/api/public/hooks/organize-drive'
      preLoaderRoute: typeof ApiPublicHooksOrganizeDriveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/find-folder': {
      id: '/api/public/hooks/find-folder'
      path: '/api/public/hooks/find-folder'
      fullPath: '/api/public/hooks/find-folder'
      preLoaderRoute: typeof ApiPublicHooksFindFolderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminNewRoute: typeof AdminNewRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminNewRoute: AdminNewRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  IntakeRoute: IntakeRoute,
  LoginRoute: LoginRoute,
  PerformanceReportRoute: PerformanceReportRoute,
  ApiDriveCustomerFilesRoute: ApiDriveCustomerFilesRoute,
  ApiDriveUploadRoute: ApiDriveUploadRoute,
  ApiImportCalendarRoute: ApiImportCalendarRoute,
  ApiPrefillReportRoute: ApiPrefillReportRoute,
  ApiSendReportRoute: ApiSendReportRoute,
  ApiSyncCalendarRoute: ApiSyncCalendarRoute,
  JobsIdRoute: JobsIdRoute,
  ApiPublicHooksFindFolderRoute: ApiPublicHooksFindFolderRoute,
  ApiPublicHooksOrganizeDriveRoute: ApiPublicHooksOrganizeDriveRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
